language: minimal

services:
  - docker

env:
  global:
    # DOCKER_USERNAME
    - secure: WTYcy6lCZlptL03N5A2ZfeTGpX/cuXE0/vrtmtSM/Lvtg0L31Uh/0g0fv8jiY7jjZAzrRL8e2CChHKmCyyPyx+qvxsbJ4HAnWmi56EnNeZMVgl2WrA5vMEJvfV0xkAxfEZ3SSdBEmNXmdMp5c6plbnpoc49VJxA9OHEC1YbbMYnIZ0FPJ3/ic/3fFH4vKOB1runM5fOlzs8cKfJyY0kp6R5bedE7UNWtcQ6LcysoPzCGeW6Snfe0PI6DCVfpvyg9pHNlgyohKzEhqEHF95hcVDfw5nc2edJYHISHCL+E6aSUM5C3jRZh9kaE/vItD1u9eoTQL1uun00MgzmXxkKjoG0t+H7po0XLPpXY5dx72Iz1qBaBZnIGy7Rfm6d+BK2tey3nE/ANBuNl3phPNR6e8TE7sAkjcY1AdkgF53xeqe4wgJoh2gM1rqXS5elimY//+X1yuumo2QI9wzf8U+0mMT+wuwIh6YwDHZv3Zy41OqTdqOCxH/zofi8j/Msrue8f7szwFks3b1vldRoL2whV5LQkF5ROiHSnSbeaNt2YFc5xvgSSw64QKjcpIZaLq1kEAQl//uFABLNtzGBzfi8+PmSyo3fp7bOOADA6h4gUePayo6oPGHSHHwYgASiCN8M779sFvNObgLYS3G025khw2SKpJ3KOpFek4nluqmJV10U=
    # DOCKER_PASSWORD
    - secure: iWLDapPN4F9DCQ10AMo6fC9KYCIg+Q9E3a1f7WUfzQOeHeKvAWAR8QriywTMSLL4FY42hK7j3AAsMwnSo9/ohMnkYWeMGgY3Y1K9afrrXy4obL+IpYMwM6XN66jZuSjhk8Fm46nHeuhJkLpGU8EgdTbcq0r19A4Q/TmWHFtmWouv8gz0AnVIfC0xayfFcoWj+blxuDPN7voAD4lNaGWjZAXBrrXf0bfr/qsvxMtT5ijPKQ2DsBJETFmuwiVkpcB0M0XBX+4bAH/59GmvBSeRp68nYC70HQkALYK8/7jay3qHHXJn3i4UdpoC6Vzc1G0uxvDLBxPo01mpe5XqMUxtsAlsappow4MbRsEz6lw9NEYSLzBCFuJ6INuYBGfnxOC+jckAuckskSYE7ipMSbSexEv15/VX0Kquf/1E73ckhAogCKyaxxAC9I2zKWZWhKkTuDeie83b1DKOjuxzLce+7B9P7NqoD+LHGRCuhv1qosRP6Tq/zDv2OYC8kYOdFZ+Fm2xKrO2aSLZQF266M6Dd+HQll9QqUQOGxNMfKKAE9Pg6s5bDMcoesv9vnRt84fgH2aE4jvMLX3wCeQkD3zxvlIUTdjnl3GOjC3qpcRnOS/nULNm6OE/aW3xxOyYfKYA+1YjAapLeGkzARthW6jinluoGWDw8wlId/BgVLWO3nTg=
    - BUILD_IMAGES_COUNT=4
    - BUILD_IMAGES_1=pyenv
    - BUILD_IMAGES_2=tox-base
    - BUILD_IMAGES_3=tox
    - BUILD_IMAGES_4=circleci-tox

script:
  - |
    set -eux
    idx=0
    while ((idx++ < BUILD_IMAGES_COUNT)); do
      build_image="BUILD_IMAGES_$idx"
      docker build -t "${DOCKER_USERNAME:-images}/${!build_image}:latest" "docker-${!build_image}"
    done

after_success:
  - |
    if [[ $TRAVIS_BRANCH != "master" ]]; then
      echo "Not on master, skipping deploy."
      exit 0
    fi
  - |
    if [[ -z $DOCKER_USERNAME || -z "DOCKER_PASSWORD" ]]; then
      echo 'Missing required $DOCKER_USERNAME and/or $DOCKER_PASSWORD!' >&2
      exit 1
    fi
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    set -eux
    idx=0
    while ((idx++ < BUILD_IMAGES_COUNT)); do
      build_image="BUILD_IMAGES_$idx"
      docker push "$DOCKER_USERNAME/${!build_image}"
    done
