language: minimal

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=demosdemon
    # DOCKER_PASSWORD
    - secure: iWLDapPN4F9DCQ10AMo6fC9KYCIg+Q9E3a1f7WUfzQOeHeKvAWAR8QriywTMSLL4FY42hK7j3AAsMwnSo9/ohMnkYWeMGgY3Y1K9afrrXy4obL+IpYMwM6XN66jZuSjhk8Fm46nHeuhJkLpGU8EgdTbcq0r19A4Q/TmWHFtmWouv8gz0AnVIfC0xayfFcoWj+blxuDPN7voAD4lNaGWjZAXBrrXf0bfr/qsvxMtT5ijPKQ2DsBJETFmuwiVkpcB0M0XBX+4bAH/59GmvBSeRp68nYC70HQkALYK8/7jay3qHHXJn3i4UdpoC6Vzc1G0uxvDLBxPo01mpe5XqMUxtsAlsappow4MbRsEz6lw9NEYSLzBCFuJ6INuYBGfnxOC+jckAuckskSYE7ipMSbSexEv15/VX0Kquf/1E73ckhAogCKyaxxAC9I2zKWZWhKkTuDeie83b1DKOjuxzLce+7B9P7NqoD+LHGRCuhv1qosRP6Tq/zDv2OYC8kYOdFZ+Fm2xKrO2aSLZQF266M6Dd+HQll9QqUQOGxNMfKKAE9Pg6s5bDMcoesv9vnRt84fgH2aE4jvMLX3wCeQkD3zxvlIUTdjnl3GOjC3qpcRnOS/nULNm6OE/aW3xxOyYfKYA+1YjAapLeGkzARthW6jinluoGWDw8wlId/BgVLWO3nTg=
    - BUILD_IMAGES_COUNT=4
    - BUILD_IMAGES_1=pyenv
    - BUILD_IMAGES_2=tox-base
    - BUILD_IMAGES_3=tox
    - BUILD_IMAGES_4=circleci-tox

before_script:
  - if [[ "$DOCKER_PASSWORD" ]]; then echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi

script:
  - |
    set -eux
    idx=0
    for build_image in $(seq -f 'BUILD_IMAGES_%.0f' 1 $BUILD_IMAGES_COUNT); do
      printf 'travis_fold:%s:%s\n' "start" "${!build_image}"
      image="$DOCKER_USERNAME/${!build_image}:latest"
      docker build --cache-from "$image" -t "$image" "docker-${!build_image}"
      if [[ "$TRAVIS_BRANCH" == "master" && "$DOCKER_PASSWORD" ]]; then
        printf 'Uploading %s/%s:latest\n' "$DOCKER_USERNAME" "${!build_image}"
        docker push "$DOCKER_USERNAME/${!build_image}:latest"
      else
        printf 'Not uploading.\n'
      fi
      printf 'travis_fold:%s:%s\n' "end" "${!build_image}"
    done
