language: minimal

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=demosdemon
    # DOCKER_PASSWORD
    - secure: iWLDapPN4F9DCQ10AMo6fC9KYCIg+Q9E3a1f7WUfzQOeHeKvAWAR8QriywTMSLL4FY42hK7j3AAsMwnSo9/ohMnkYWeMGgY3Y1K9afrrXy4obL+IpYMwM6XN66jZuSjhk8Fm46nHeuhJkLpGU8EgdTbcq0r19A4Q/TmWHFtmWouv8gz0AnVIfC0xayfFcoWj+blxuDPN7voAD4lNaGWjZAXBrrXf0bfr/qsvxMtT5ijPKQ2DsBJETFmuwiVkpcB0M0XBX+4bAH/59GmvBSeRp68nYC70HQkALYK8/7jay3qHHXJn3i4UdpoC6Vzc1G0uxvDLBxPo01mpe5XqMUxtsAlsappow4MbRsEz6lw9NEYSLzBCFuJ6INuYBGfnxOC+jckAuckskSYE7ipMSbSexEv15/VX0Kquf/1E73ckhAogCKyaxxAC9I2zKWZWhKkTuDeie83b1DKOjuxzLce+7B9P7NqoD+LHGRCuhv1qosRP6Tq/zDv2OYC8kYOdFZ+Fm2xKrO2aSLZQF266M6Dd+HQll9QqUQOGxNMfKKAE9Pg6s5bDMcoesv9vnRt84fgH2aE4jvMLX3wCeQkD3zxvlIUTdjnl3GOjC3qpcRnOS/nULNm6OE/aW3xxOyYfKYA+1YjAapLeGkzARthW6jinluoGWDw8wlId/BgVLWO3nTg=
    - BUILD_IMAGES_COUNT=4
    - BUILD_IMAGES_1=pyenv
    - BUILD_IMAGES_2=tox-base
    - BUILD_IMAGES_3=tox
    - BUILD_IMAGES_4=circleci-tox

script:
  - |
    set -eux
    idx=0
    while ((idx++ < BUILD_IMAGES_COUNT)); do
      build_image="BUILD_IMAGES_$idx"
      printf 'travis_fold:%s:%s' "start" "${!build_image}"
      docker pull "$DOCKER_USERNAME/${!build_image}:latest" || true
      docker build -t "$DOCKER_USERNAME/${!build_image}:latest" "docker-${!build_image}"
      printf 'travis_fold:%s:%s' "end" "${!build_image}"
    done

after_success:
  - |
    if [[ $TRAVIS_BRANCH != "master" ]]; then
      echo "Not on master, skipping deploy."
      exit 0
    fi
  - |
    if [[ -z $DOCKER_USERNAME || -z "DOCKER_PASSWORD" ]]; then
      echo 'Missing required $DOCKER_USERNAME and/or $DOCKER_PASSWORD!' >&2
      exit 1
    fi
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    set -eux
    idx=0
    while ((idx++ < BUILD_IMAGES_COUNT)); do
      build_image="BUILD_IMAGES_$idx"
      docker push "$DOCKER_USERNAME/${!build_image}"
    done
